version: 2
project_name: wechatpay-notify-gateway

builds:
  - id: gateway
    binary: gateway
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w --extldflags "-static"

upx:
  - enabled: true
    # Filter by build ID.
    ids:
      - gateway
    # Compress argument.
    # Valid options are from '1' (faster) to '9' (better), and 'best'.
    compress: best
    # Whether to try LZMA (slower).
    lzma: true
    # Whether to try all methods and filters (slow).
    brute: false

archives:
  - id: gateway
    builds:
      - gateway
    formats: [ "zip", "tar.gz", "tar.xz" ]
    wrap_in_directory: false
    strip_binary_directory: true
    files:
      - LICENSE
      - config.example.yml
